### ISSUE TITLE
SMTP.getreply() infinite loop when the operation is cancelled

### ISSUE THREAD

**Issue by iceboy233** [hwmrocker/smtplibaio#2]
``` python
future = asyncio.Future()

def callback():
    future.set_result(True)

self._loop.add_reader(self.file, callback)
yield from future
self._loop.remove_reader(self.file)
```

This causes infinite loop when the future is cancelled before the callback is invoked.

Add `future.cancel()` before add_reader reproduces the error.

**Comment by hwmrocker** [comment]
hi,
thx for reporting a bug but I don't see the problem from the portion of code you provided.

can you provide a small complete test case that results in this inifinite loop?

**Comment by iceboy233** [comment]
We have built a website, which sends a mail on HTTP request. Whenever user clicks the stop button on the browser before the mail is sent, the server goes into infinite loop and generates huge amount of error logs.

A exact test case to trigger the problem may require exact timing which may be unstable. However, there are many other ways to trigger the problem. I crafted this code which can always trigger the problem:

``` python
import asyncio
import smtplibaio

def foo():
  smtp = smtplibaio.SMTP()
  yield from smtp.connect('smtp.gmail.com')

loop = asyncio.get_event_loop()
loop.create_task(foo())
loop.run_forever()
```

See if you find out how it works :grin:

**Comment by hwmrocker** [comment]
is this issue fixed with the pull request?

**Comment by iceboy233** [comment]
I think so. Do you have any concerns?

**Comment by hwmrocker** [comment]
no, thats great to hear. Otherwise I would try to get some time on the weekend to investigate.

**Comment by iceboy233** [comment]
It will be great if you bump the version number and push to pypi. Thanks.

**Comment by hwmrocker** [comment]
thx for the reminder. I just published it
