### ISSUE TITLE
Example issues

### ISSUE THREAD

**Issue by thijstriemstra** [hwmrocker/smtplibaio#7]
With the 2nd example in the readme, e.g.:

```python
async with SMTP_SSL(hostname=host, port=port) as client:
```
I get this traceback:

```
  File "/Users/me/projects/foo/bar/mail.py", line 118, in sendemail
    async with SMTP_SSL(hostname=host, port=port) as client:
Uncaught exception <class 'TypeError'>: __init__() got an unexpected keyword argument 'hostname'
```
When I leave the keywords alone it seems to work fine:

```python
async with SMTP_SSL(host, port) as client:
```

Finally, there's a traceback when disconnecting:

```
  File "/Users/me/projects/foo/mail.py", line 128, in sendemail
    msg.as_string())
  File "/Users/me/.virtualenvs/foo/lib/python3.5/site-packages/smtplibaio.py", line 315, in __aexit__
    self.close()
  File "/Users/me/.virtualenvs/foo/lib/python3.5/site-packages/smtplibaio.py", line 940, in close
    sock = self.sock
Uncaught exception <class 'AttributeError'>: 'SMTP_SSL' object has no attribute 'sock'
```

**Comment by thijstriemstra** [comment]
This was tested against a local SMTP server (both running python 3.5.1 on osx 10.11):

```
python -m smtpd -n -c DebuggingServer localhost:1025
```

Looks like the `AttributeError: 'SMTP_SSL' object has no attribute 'sock'` also appears when it's connecting to a non-existing server, which looks like a bug to me. I'll now try to setup a local SSL server for testing and try again.

Update: same sock error with a live gmail server, e.g. `smtp.gmail.com` on port 465.

**Comment by Frzk** [comment]
To me it seems like you're trying to run the example with an old version of the package.

Since version 2.0.0, the use of sockets has been replaced by the higher-level streams API. So any issue related to ``sock`` certainly refers to a previous version of smtplibaio.

Also, if you [check the source code](https://github.com/hwmrocker/smtplibaio/blob/master/smtplibaio/smtp.py#L1123), you will see that ``SMTP_SSL.__init__`` actually has a named argument called ``hostname``.

Please make sure you are using 2.0.0 and have fun with smtplibaio :-)

(I just checked, and for some reason, it seems like PyPi isn't offering 2.0.0 for download - see https://pypi.python.org/simple/smtplibaio/ -, although it's been uploaded a few days ago. That's something @hwmrocker might want to look at.)

(Even the github releases page seems weird : https://github.com/hwmrocker/smtplibaio/releases . Another job for @hwmrocker :-P)

**Comment by thijstriemstra** [comment]
> (I just checked, and for some reason, it seems like PyPi isn't offering 2.0.0 for download - see https://pypi.python.org/simple/smtplibaio/ -, although it's been uploaded a few days ago. That's something @hwmrocker might want to look at.)

Yeah that's where the confusion started. I'll have to test a git clone at some point.

**Comment by hwmrocker** [comment]
@thijstriemstra thanks for this info i will look this evening into this issue

**Comment by hwmrocker** [comment]
m( i just registered the new package on pypi and forgot to run
`python setup.py sdist upload`
now the new version should be available

**Comment by thijstriemstra** [comment]
Unfortunately it's still very broken. Did you test it?

Try installing it and then uninstall it, you'll see there are no source files installed:

```
$ pip install smtplibaio
Collecting smtplibaio
Installing collected packages: smtplibaio
Successfully installed smtplibaio-2.0.0

$ pip uninstall smtplibaio
Uninstalling smtplibaio-2.0.0:
  /Users/foo/.virtualenvs/bar/lib/python3.5/site-packages/smtplibaio-2.0.0.dist-info/DESCRIPTION.rst
  /Users/foo/.virtualenvs/bar/lib/python3.5/site-packages/smtplibaio-2.0.0.dist-info/INSTALLER
  /Users/foo/.virtualenvs/bar/lib/python3.5/site-packages/smtplibaio-2.0.0.dist-info/METADATA
  /Users/foo/.virtualenvs/bar/python3.5/site-packages/smtplibaio-2.0.0.dist-info/RECORD
  /Users/foo/.virtualenvs/bar/lib/python3.5/site-packages/smtplibaio-2.0.0.dist-info/WHEEL
  /Users/foo/.virtualenvs/bar/lib/python3.5/site-packages/smtplibaio-2.0.0.dist-info/metadata.json
  /Users/foo/.virtualenvs/bar/lib/python3.5/site-packages/smtplibaio-2.0.0.dist-info/top_level.txt
Proceed (y/n)?
```

Add a MANIFEST.in file that defines what to package.

**Comment by Frzk** [comment]
I don't think the MANIFEST.in file is mandatory, but the uploaded tarball is clearly almost empty and should be fixed.

**Comment by hwmrocker** [comment]
sorry for the inconvenience. I uploaded the new package.
We should create a test for this.
I will do this next week, when i have time again.
